
name: Run Coverity On Polaris
on: [release]

jobs:
  synopsys_coverity:
    name: Synopsys Coverity
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    #- name: Build with Maven
    #  run: mvn -B package --file pom.xml
           
    - name: Download Coverity Analysis Engine
      run: |
        curl http://52.188.212.142:8080/downloadFile.htm?fn=cov-analysis-linux64-2020.06.tar.gz -o cov-analysis-linux64-2020.06.tar.gz -LO -u admin:SIGpass8!
        tar -xf cov-analysis-linux64-2020.06.tar.gz
        curl http://52.188.212.142:8080/downloadFile.htm?fn=analysis-license.dat -o license.dat -LO -u admin:SIGpass8!
        mv license.dat ./cov-analysis-linux64-2020.06/bin
        
    - name: Cov-Build              
      run: |
        ./cov-analysis-linux64-2020.06/bin/cov-configure --java
        ./cov-analysis-linux64-2020.06/bin/cov-build --dir idir mvn install
    
    - name: Cov-Analyze
      run: |
        ./cov-analysis-linux64-2020.06/bin/cov-analyze --dir idir --webapp-security
        
      
    #- name: npm install
    #  run: npm install        
        
    #- name: Synopsys Detect Action
    
#  uses: blackducksoftware/github-action@1.0.1
 #     env:
  #      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL}}
   #     BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN}}
